info:
  namespace: pilesfix
items:
  bones_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882600
      generate: false
      model_path: item/pile_bones/bones_1
  bones_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882601
      generate: false
      model_path: item/pile_bones/bones_1
  bones_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882602
      generate: false
      model_path: item/pile_bones/bones_2
  bones_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882603
      generate: false
      model_path: item/pile_bones/bones_2
  bones_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882604
      generate: false
      model_path: item/pile_bones/bones_3
  bones_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882605
      generate: false
      model_path: item/pile_bones/bones_3
  bones_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882606
      generate: false
      model_path: item/pile_bones/bones_4
  bones_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882607
      generate: false
      model_path: item/pile_bones/bones_4
  bones_5:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882608
      generate: false
      model_path: item/pile_bones/bones_5
  bones_5:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882609
      generate: false
      model_path: item/pile_bones/bones_5
  bones_6:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882610
      generate: false
      model_path: item/pile_bones/bones_6
  bones_6:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882611
      generate: false
      model_path: item/pile_bones/bones_6
  bones_7:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882612
      generate: false
      model_path: item/pile_bones/bones_7
  bones_7:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882613
      generate: false
      model_path: item/pile_bones/bones_7
  bones_8:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882614
      generate: false
      model_path: item/pile_bones/bones_8
  bones_8:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: BONE
      model_id: 1882615
      generate: false
      model_path: item/pile_bones/bones_8