info:
  namespace: pilesfix
items:
  sugar_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882600
      generate: false
      model_path: item/pile_jars/sugar/sugar_1
  sugar_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882601
      generate: false
      model_path: item/pile_jars/sugar/sugar_2
  sugar_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882602
      generate: false
      model_path: item/pile_jars/sugar/sugar_3
  sugar_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882603
      generate: false
      model_path: item/pile_jars/sugar/sugar_4
  sugar_5:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882604
      generate: false
      model_path: item/pile_jars/sugar/sugar_5
  sugar_6:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882605
      generate: false
      model_path: item/pile_jars/sugar/sugar_6
  sugar_7:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882606
      generate: false
      model_path: item/pile_jars/sugar/sugar_7
  sugar_8:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882607
      generate: false
      model_path: item/pile_jars/sugar/sugar_8
  sugar_9:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882608
      generate: false
      model_path: item/pile_jars/sugar/sugar_9
  sugar_10:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882609
      generate: false
      model_path: item/pile_jars/sugar/sugar_10
  sugar_11:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882610
      generate: false
      model_path: item/pile_jars/sugar/sugar_11
  sugar_12:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882611
      generate: false
      model_path: item/pile_jars/sugar/sugar_12
  sugar_13:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882612
      generate: false
      model_path: item/pile_jars/sugar/sugar_13
  sugar_14:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882613
      generate: false
      model_path: item/pile_jars/sugar/sugar_14
  sugar_15:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882614
      generate: false
      model_path: item/pile_jars/sugar/sugar_15
  sugar_16:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CLAY_BALL
      model_id: 1882615
      generate: false
      model_path: item/pile_jars/sugar/sugar_16