info:
  namespace: pilesfix
items:
  coal_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882600
      generate: false
      model_path: item/pile_coal/coal_1
  coal_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882601
      generate: false
      model_path: item/pile_coal/coal_2
  coal_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882602
      generate: false
      model_path: item/pile_coal/coal_3
  coal_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882603
      generate: false
      model_path: item/pile_coal/coal_4
  coal_5:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882604
      generate: false
      model_path: item/pile_coal/coal_5
  coal_6:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882605
      generate: false
      model_path: item/pile_coal/coal_6
  coal_7:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882606
      generate: false
      model_path: item/pile_coal/coal_7
  coal_8:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882607
      generate: false
      model_path: item/pile_coal/coal_8
  coal_9:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882608
      generate: false
      model_path: item/pile_coal/coal_9
  coal_10:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882609
      generate: false
      model_path: item/pile_coal/coal_10
  coal_11:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882610
      generate: false
      model_path: item/pile_coal/coal_11
  coal_12:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882611
      generate: false
      model_path: item/pile_coal/coal_12
  coal_13:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882612
      generate: false
      model_path: item/pile_coal/coal_13
  coal_14:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882613
      generate: false
      model_path: item/pile_coal/coal_14
  coal_15:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882614
      generate: false
      model_path: item/pile_coal/coal_15
  coal_16:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882615
      generate: false
      model_path: item/pile_coal/coal_16
  coal_17:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882616
      generate: false
      model_path: item/pile_coal/coal_17
  coal_18:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882617
      generate: false
      model_path: item/pile_coal/coal_18
  coal_19:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882618
      generate: false
      model_path: item/pile_coal/coal_19
  coal_20:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: COAL
      model_id: 1882619
      generate: false
      model_path: item/pile_coal/coal_20