info:
  namespace: pilesfix
items:
  stacked_tuff_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882600
      generate: false
      model_path: item/pile_tuff/stacked_tuff_1
  stacked_tuff_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882601
      generate: false
      model_path: item/pile_tuff/stacked_tuff_2
  stacked_tuff_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882602
      generate: false
      model_path: item/pile_tuff/stacked_tuff_3
  stacked_tuff_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882603
      generate: false
      model_path: item/pile_tuff/stacked_tuff_4
  stacked_tuff_5:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882604
      generate: false
      model_path: item/pile_tuff/stacked_tuff_5
  stacked_tuff_6:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882605
      generate: false
      model_path: item/pile_tuff/stacked_tuff_6
  stacked_tuff_7:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882606
      generate: false
      model_path: item/pile_tuff/stacked_tuff_7
  stacked_tuff_8:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882607
      generate: false
      model_path: item/pile_tuff/stacked_tuff_8
  stacked_tuff_9:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882608
      generate: false
      model_path: item/pile_tuff/stacked_tuff_9
  stacked_tuff_10:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882609
      generate: false
      model_path: item/pile_tuff/stacked_tuff_10
  stacked_tuff_11:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882610
      generate: false
      model_path: item/pile_tuff/stacked_tuff_11
  stacked_tuff_12:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882611
      generate: false
      model_path: item/pile_tuff/stacked_tuff_12
  stacked_tuff_13:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882612
      generate: false
      model_path: item/pile_tuff/stacked_tuff_13
  stacked_tuff_14:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882613
      generate: false
      model_path: item/pile_tuff/stacked_tuff_14
  stacked_tuff_15:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882614
      generate: false
      model_path: item/pile_tuff/stacked_tuff_15
  stacked_tuff_16:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882615
      generate: false
      model_path: item/pile_tuff/stacked_tuff_16
  stacked_tuff_17:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882616
      generate: false
      model_path: item/pile_tuff/stacked_tuff_17
  stacked_tuff_18:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882617
      generate: false
      model_path: item/pile_tuff/stacked_tuff_18
  stacked_tuff_19:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882618
      generate: false
      model_path: item/pile_tuff/stacked_tuff_19
  stacked_tuff_20:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882619
      generate: false
      model_path: item/pile_tuff/stacked_tuff_20
  stacked_tuff_21:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882620
      generate: false
      model_path: item/pile_tuff/stacked_tuff_21
  stacked_tuff_22:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882621
      generate: false
      model_path: item/pile_tuff/stacked_tuff_22
  stacked_tuff_23:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882622
      generate: false
      model_path: item/pile_tuff/stacked_tuff_23
  stacked_tuff_24:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: CYAN_DYE
      model_id: 1882623
      generate: false
      model_path: item/pile_tuff/stacked_tuff_24