info:
  namespace: pilesfix
items:
  pile_diamonds_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882600
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_1
  pile_diamonds_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882601
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_2
  pile_diamonds_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882602
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_3
  pile_diamonds_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882603
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_4
  pile_diamonds_5:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882604
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_5
  pile_diamonds_6:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882605
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_6
  pile_diamonds_7:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882606
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_7
  pile_diamonds_8:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882607
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_8
  pile_diamonds_9:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882608
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_9
  pile_diamonds_10:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882609
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_10
  pile_diamonds_11:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882610
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_11
  pile_diamonds_12:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882611
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_12
  pile_diamonds_13:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882612
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_13
  pile_diamonds_14:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882613
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_14
  pile_diamonds_15:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882614
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_15
  pile_diamonds_16:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882615
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_16
  pile_diamonds_17:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882616
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_17
  pile_diamonds_18:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882617
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_18
  pile_diamonds_19:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882618
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_19
  pile_diamonds_20:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882619
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_20
  pile_diamonds_21:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882620
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_21
  pile_diamonds_22:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882621
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_22
  pile_diamonds_23:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882622
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_23
  pile_diamonds_24:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DIAMOND
      model_id: 1882623
      generate: false
      model_path: item/pile_diamonds/pile_diamonds_24