info:
  namespace: pilesfix
items:
  dragon_breath_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DRAGON_BREATH
      model_id: 1882600
      generate: false
      model_path: item/pile_potions/dragon_breath_1
  dragon_breath_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DRAGON_BREATH
      model_id: 1882601
      generate: false
      model_path: item/pile_potions/dragon_breath_2
  dragon_breath_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DRAGON_BREATH
      model_id: 1882602
      generate: false
      model_path: item/pile_potions/dragon_breath_3
  dragon_breath_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: DRAGON_BREATH
      model_id: 1882603
      generate: false
      model_path: item/pile_potions/dragon_breath_4