info:
  namespace: pilesfix
items:
  empty_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLASS_BOTTLE
      model_id: 1882600
      generate: false
      model_path: item/pile_potions/empty_1
  empty_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLASS_BOTTLE
      model_id: 1882601
      generate: false
      model_path: item/pile_potions/empty_2
  empty_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLASS_BOTTLE
      model_id: 1882602
      generate: false
      model_path: item/pile_potions/empty_3
  empty_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLASS_BOTTLE
      model_id: 1882603
      generate: false
      model_path: item/pile_potions/empty_4