info:
  namespace: pilesfix
items:
  glow_berries_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882600
      generate: false
      model_path: item/pile_jars/berries/glow_berries_1
  glow_berries_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882601
      generate: false
      model_path: item/pile_jars/berries/glow_berries_2
  glow_berries_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882602
      generate: false
      model_path: item/pile_jars/berries/glow_berries_3
  glow_berries_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882603
      generate: false
      model_path: item/pile_jars/berries/glow_berries_4
  glow_berries_5:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882604
      generate: false
      model_path: item/pile_jars/berries/glow_berries_5
  glow_berries_6:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882605
      generate: false
      model_path: item/pile_jars/berries/glow_berries_6
  glow_berries_7:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882606
      generate: false
      model_path: item/pile_jars/berries/glow_berries_7
  glow_berries_8:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882607
      generate: false
      model_path: item/pile_jars/berries/glow_berries_8
  glow_berries_9:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882608
      generate: false
      model_path: item/pile_jars/berries/glow_berries_9
  glow_berries_10:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882609
      generate: false
      model_path: item/pile_jars/berries/glow_berries_10
  glow_berries_11:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882610
      generate: false
      model_path: item/pile_jars/berries/glow_berries_11
  glow_berries_12:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882611
      generate: false
      model_path: item/pile_jars/berries/glow_berries_12
  glow_berries_13:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882612
      generate: false
      model_path: item/pile_jars/berries/glow_berries_13
  glow_berries_14:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882613
      generate: false
      model_path: item/pile_jars/berries/glow_berries_14
  glow_berries_15:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882614
      generate: false
      model_path: item/pile_jars/berries/glow_berries_15
  glow_berries_16:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: GLOW_BERRIES
      model_id: 1882615
      generate: false
      model_path: item/pile_jars/berries/glow_berries_16