info:
  namespace: pilesfix
items:
  stacked_andesite_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882600
      generate: false
      model_path: item/pile_andesite/stacked_andesite_1
  stacked_andesite_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882601
      generate: false
      model_path: item/pile_andesite/stacked_andesite_2
  stacked_andesite_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882602
      generate: false
      model_path: item/pile_andesite/stacked_andesite_3
  stacked_andesite_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882603
      generate: false
      model_path: item/pile_andesite/stacked_andesite_4
  stacked_andesite_5:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882604
      generate: false
      model_path: item/pile_andesite/stacked_andesite_5
  stacked_andesite_6:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882605
      generate: false
      model_path: item/pile_andesite/stacked_andesite_6
  stacked_andesite_7:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882606
      generate: false
      model_path: item/pile_andesite/stacked_andesite_7
  stacked_andesite_8:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882607
      generate: false
      model_path: item/pile_andesite/stacked_andesite_8
  stacked_andesite_9:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882608
      generate: false
      model_path: item/pile_andesite/stacked_andesite_9
  stacked_andesite_10:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882609
      generate: false
      model_path: item/pile_andesite/stacked_andesite_10
  stacked_andesite_11:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882610
      generate: false
      model_path: item/pile_andesite/stacked_andesite_11
  stacked_andesite_12:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882611
      generate: false
      model_path: item/pile_andesite/stacked_andesite_12
  stacked_andesite_13:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882612
      generate: false
      model_path: item/pile_andesite/stacked_andesite_13
  stacked_andesite_14:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882613
      generate: false
      model_path: item/pile_andesite/stacked_andesite_14
  stacked_andesite_15:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882614
      generate: false
      model_path: item/pile_andesite/stacked_andesite_15
  stacked_andesite_16:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882615
      generate: false
      model_path: item/pile_andesite/stacked_andesite_16
  stacked_andesite_17:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882616
      generate: false
      model_path: item/pile_andesite/stacked_andesite_17
  stacked_andesite_18:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882617
      generate: false
      model_path: item/pile_andesite/stacked_andesite_18
  stacked_andesite_19:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882618
      generate: false
      model_path: item/pile_andesite/stacked_andesite_19
  stacked_andesite_20:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882619
      generate: false
      model_path: item/pile_andesite/stacked_andesite_20
  stacked_andesite_21:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882620
      generate: false
      model_path: item/pile_andesite/stacked_andesite_21
  stacked_andesite_22:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882621
      generate: false
      model_path: item/pile_andesite/stacked_andesite_22
  stacked_andesite_23:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882622
      generate: false
      model_path: item/pile_andesite/stacked_andesite_23
  stacked_andesite_24:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: LIGHT_GRAY_DYE
      model_id: 1882623
      generate: false
      model_path: item/pile_andesite/stacked_andesite_24