info:
  namespace: pilesfix
items:
  redstone_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882600
      generate: false
      model_path: item/pile_jars/redstone/redstone_1
  redstone_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882601
      generate: false
      model_path: item/pile_jars/redstone/redstone_2
  redstone_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882602
      generate: false
      model_path: item/pile_jars/redstone/redstone_3
  redstone_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882603
      generate: false
      model_path: item/pile_jars/redstone/redstone_4
  redstone_5:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882604
      generate: false
      model_path: item/pile_jars/redstone/redstone_5
  redstone_6:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882605
      generate: false
      model_path: item/pile_jars/redstone/redstone_6
  redstone_7:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882606
      generate: false
      model_path: item/pile_jars/redstone/redstone_7
  redstone_8:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882607
      generate: false
      model_path: item/pile_jars/redstone/redstone_8
  redstone_9:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882608
      generate: false
      model_path: item/pile_jars/redstone/redstone_9
  redstone_10:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882609
      generate: false
      model_path: item/pile_jars/redstone/redstone_10
  redstone_11:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882610
      generate: false
      model_path: item/pile_jars/redstone/redstone_11
  redstone_12:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882611
      generate: false
      model_path: item/pile_jars/redstone/redstone_12
  redstone_13:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882612
      generate: false
      model_path: item/pile_jars/redstone/redstone_13
  redstone_14:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882613
      generate: false
      model_path: item/pile_jars/redstone/redstone_14
  redstone_15:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882614
      generate: false
      model_path: item/pile_jars/redstone/redstone_15
  redstone_16:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: REDSTONE
      model_id: 1882615
      generate: false
      model_path: item/pile_jars/redstone/redstone_16