info:
  namespace: pilesfix
items:
  berries_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882600
      generate: false
      model_path: item/pile_jars/berries/berries_1
  berries_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882601
      generate: false
      model_path: item/pile_jars/berries/berries_2
  berries_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882602
      generate: false
      model_path: item/pile_jars/berries/berries_3
  berries_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882603
      generate: false
      model_path: item/pile_jars/berries/berries_4
  berries_5:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882604
      generate: false
      model_path: item/pile_jars/berries/berries_5
  berries_6:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882605
      generate: false
      model_path: item/pile_jars/berries/berries_6
  berries_7:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882606
      generate: false
      model_path: item/pile_jars/berries/berries_7
  berries_8:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882607
      generate: false
      model_path: item/pile_jars/berries/berries_8
  berries_9:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882608
      generate: false
      model_path: item/pile_jars/berries/berries_9
  berries_10:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882609
      generate: false
      model_path: item/pile_jars/berries/berries_10
  berries_11:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882610
      generate: false
      model_path: item/pile_jars/berries/berries_11
  berries_12:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882611
      generate: false
      model_path: item/pile_jars/berries/berries_12
  berries_13:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882612
      generate: false
      model_path: item/pile_jars/berries/berries_13
  berries_14:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882613
      generate: false
      model_path: item/pile_jars/berries/berries_14
  berries_15:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882614
      generate: false
      model_path: item/pile_jars/berries/berries_15
  berries_16:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: SWEET_BERRIES
      model_id: 1882615
      generate: false
      model_path: item/pile_jars/berries/berries_16