info:
  namespace: pilesfix
items:
  totem_1:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: TOTEM_OF_UNDYING
      model_id: 1882600
      generate: false
      model_path: item/pile_totems/totem_1
  totem_2:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: TOTEM_OF_UNDYING
      model_id: 1882601
      generate: false
      model_path: item/pile_totems/totem_2
  totem_3:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: TOTEM_OF_UNDYING
      model_id: 1882602
      generate: false
      model_path: item/pile_totems/totem_3
  totem_4:
    display_name: pilesfix
    permission: pilesfix
    resource:
      material: TOTEM_OF_UNDYING
      model_id: 1882603
      generate: false
      model_path: item/pile_totems/totem_4